<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Platforms>AnyCPU;x64</Platforms>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOSPlatform('windows'))">win-x64</RuntimeIdentifier>
    <ApplicationIcon>Assets\storeIcon.ico</ApplicationIcon>
    <NoWarn>$(NoWarn);NU1701;CS8767;CS8625;CS8602;CS8600;CS8604</NoWarn>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="BouncyCastle.Cryptography" />
    <TrimmerRootAssembly Include="TagLibSharp" />
    <TrimmerRootAssembly Include="RabbitMQ.Client" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.IO.Ports" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="Resources\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageReference Include="FluentAvaloniaUI" Version="3.0.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.0.0" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.5.0" />
    <PackageReference Include="NModbus4" Version="2.1.0" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="System.IO.Ports" Version="10.0.9" />
    <PackageReference Include="System.Windows.Extensions" Version="10.0.9" />
  </ItemGroup>
</Project>
